services:
  firefly-app:
    image: fireflyiii/core:latest
    hostname: firefly-app
    restart: unless-stopped
    volumes:
      - ./services-data/firefly/firefly_iii_upload:/var/www/html/storage/upload
    env_file: 
      - ./env/firefly-app.env
    depends_on:
      firefly-mariadb:
        condition: service_healthy
    networks:
      - nginx-proxy
      - firefly-network

  firefly-mariadb:
    image: mariadb:lts
    hostname: firefly-mariadb
    restart: unless-stopped
    env_file: ./env/firefly-mariadb.env
    networks:
      - firefly-network
    volumes:
      - ./services-data/firefly/firefly_iii_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "bash", "-c", "ss -lntup | grep :3306 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  firefly-cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: unless-stopped
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly-app:8080/api/v1/cron/b7f8e2d9c3a1f4b6d0e7a8c5f2b9d6e1\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly-network
