services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./services-data/mailu/redis:/data
    networks:
      - mailu-network
    dns:
      - 9.9.9.9
      - 149.112.112.112

  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ./env/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    networks:
      - nginx-proxy
      - mailu-network
      - webmail
      - radicale
    dns:
      - 9.9.9.9
      - 149.112.112.112

    volumes:
      - ./ssl-certificates/mailu:/certs:ro
      - ./ssl-certificates/mailu:/certs:ro
      - ./services-data/mailu/overrides/nginx:/overrides:ro

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ./env/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - ./services-data/mailu/data:/data
      - ./services-data/mailu/dkim:/dkim
    depends_on:
      - redis
    networks:
      - mailu-network
    dns:
      - 9.9.9.9
      - 149.112.112.112

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ./env/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - ./services-data/mailu/mail:/mail
      - ./services-data/mailu/overrides/dovecot:/overrides:ro
    networks:
      - mailu-network
    depends_on:
      - front
    dns:
      - 9.9.9.9
      - 149.112.112.112

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ./env/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - ./services-data/mailu/mailqueue:/queue
      - ./services-data/mailu/overrides/postfix:/overrides:ro
    depends_on:
      - front
    networks:
      - mailu-network
    dns:
      - 9.9.9.9
      - 149.112.112.112

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools
    dns:
      - 9.9.9.9
      - 149.112.112.112
      
  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: ./env/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - mailu-network
      - oletools
    volumes:
      - ./services-data/mailu/filter:/var/lib/rspamd
      - ./services-data/mailu/overrides/rspamd:/overrides:ro
    depends_on:
      - front
      - redis
      - oletools
    dns:
      - 9.9.9.9
      - 149.112.112.112

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2024.06}
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-webdav
    volumes:
      - "./services-data/mailu/dav:/data"
    networks:
      - radicale
    dns:
      - 9.9.9.9
      - 149.112.112.112

  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ./env/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - ./services-data/mailu/webmail:/data
      - ./services-data/mailu/overrides/roundcube:/overrides:ro
    networks:
      - webmail
    depends_on:
      - front
    dns:
      - 9.9.9.9
      - 149.112.112.112