services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    env_file:
      - ./env/wireguard.env
    volumes:
      - ./services-data/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: '1'
      net.ipv4.ip_forward: '1'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    networks:
      - nginx-proxy
